services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    container_name: els
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - erpaKabloNetwork
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.25
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - erpaKabloNetwork
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
volumes:
  elasticsearch-data:

networks:
  erpaKabloNetwork:
    driver: bridge